### ISSUE TITLE
Inconsistency between README.md and website

### ISSUE THREAD

**Issue by B3rn475** [rockstor/rockstor-installer#161] opened 2024-04-02 07:48 UTC
The README.md states

`START README.md Snippet`

## Core Profiles
Our current pre-built installers, see: [Downloads](https://rockstor.com/dls.html), are built using the following profiles:

- **Leap15.5.x86_64**
- **Leap15.5.RaspberryPi4** (supports RPi400 also)
- **Leap15.5.ARM64EFI** (N.B. Full Ten64 compatibility awaiting mcbridematt repo update)

`END README.md Snippet`
https://github.com/rockstor/rockstor-installer/blob/13eeae9a19068c2a880e376cdc736c33abd02d37/README.md?plain=1#L16C1-L21C89

While the website is still linking to the 15.4

**Comment by phillxnet** [comment] 2024-04-02 08:55
Yes, we were about to rebuild our installers and first needed the 15.5 profile here - we use this repo to build our downloadable installers of course. But we then found some existing issues in the end-to-end testing that meant the resulting installers would not work without some more fiddling. These issues have now been addressed in the more recent updates to the testing channel rpms used in this installer. See the following forum thread for that progress:

https://forum.rockstor.com/t/v5-0-testing-channel-changelog/8898

I have also begun work on the Website update partner issue/PR re the additional 15.5 move within this repo:

- "Update downloads re EOL 15.3 - 15.4 - and add 15.5": https://github.com/rockstor/rockstor-website/issues/87
- Draft PR: https://github.com/rockstor/rockstor-website/pull/92

However that will likely be revised as we are now already building and publishing testing rpms for the beta version of Leap 15.6: https://forum.rockstor.com/t/leap-15-6-support/9330

And consequently I have added the following issue in this repo:

Add Leap 15.6 profiles #162

This repo is used for our own installer builds, so we must first update there to then build and test our installer. And to enable  others to do likewise and report issues they find. That is the nature of our collaborative open source development.

You should find: if you change the versioning as indicated in the referenced README.md to our latest testing rpm (from the above forum thread) that a 15.5 installer should be fully functional. It was the last time I tried.

But form:

https://github.com/rockstor/rockstor-installer/blob/13eeae9a19068c2a880e376cdc736c33abd02d37/rockstor.kiwi#L507

This is current.

So in short, this repo is ahead of our website as our installers are used by may more folks than use this repo. And we need to know they work: and after 15.5 profile was added we had some issues in the rockstor-core (rpm code) that failed on the new OS base. But they were tended to and we have limited resource to imidiately update all our resources (website in this case). Any testing / confirmation on the new profile would of course help. If that takes your fancy :).

If you are awaiting new installers - they are on the way. But yes 5.0.8-0 was earmarked for the next installer but we are already very close to a 5.0.9-0 testing rpm release and we had the new Beta Leap come out in the interim: so some backend work was required such that we might begin building, and consequently be able to offer that in our pre-build installer matrix.

This last testing phase has changed almost all our our underlying dependencies on the Python side: and so has inevitably been a little rocky: i.e. Py2.7 to Py3.11. And our main focus in on ensuring Stable to Stable update functionality. This has necessitated quite a lot of work: but we are lamost there: hence some delays in such things as the installer builds.

But do test and report your findings as per the referenced README.md and our most recently added 15.5 profile as it all helps. And we have very limited hosting space for these installers. So the upload of new will likely necessitate some older versions being removed: see our current funding/open accounting on our Open Collective page here:

https://opencollective.com/the-rockstor-project

Hope that helps, at least with some context. Our forum is the preferred place for such enquiries incidentally as although this is actionable: we do already have the linked issue in our website repository pertaining to this inconsistency, so I'll close this issue as a duplicate of that:

Closing as:
In progress via Draft PR in website GitHub repo: https://github.com/rockstor/rockstor-website/pull/92
and indicated dependencies.

**Closed by phillxnet** 2024-04-02 08:55 UTC
